### PR TITLE
EXPLAIN ANALYSE

### PR DESCRIPTION
**Pull request by tingamapuro04**
I have worked on the query branch where I have written the queries required to create an email column, insert emails, etc. I have also used the explain analyse to test the execution time for the three queries. Below I have provided screenshots of the results
firstbefore
firstafter
secondbefore
secondafter
thirdbefore
thirdafter

### CODE REVIEW

**Comment by tingamapuro04** [comment]
The queries we have written are included in the files data.sql and schema.sql

**Review by BenMukebo — CHANGES_REQUESTED** [review]
### Hi @tingamapuro04,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


- [ ] Kindly, Add a descriptive README file to your project,  A professional README file should have a: Project title, Project description,  🛠️  List of technology used in the project, Getting Started that includes Instructions to set the project up locally as this will be of help to non-technical users.  this includes "git clone URL", "cd project_name", "npm install", "npm start", etc., you can copy and paste the content but remember to customize it to your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tingamapuro04** [comment]
I have added a proper description to the readme.md file with details about the project details.

**Review by smunozmo — APPROVED** [review]
Hi @tingamapuro04, 👋 

## Highlights 👏 

- Excellent job making the suggested changes, your DB is audited correctly, great! 😎 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 




Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
